
apiVersion: v1
kind: Service
metadata:
  name: front-v1-service
  labels:
    app: front
    version: v1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: front
    version: v1

---
apiVersion: v1
kind: Service
metadata:
  name: front-v2-service
  labels:
    app: front
    version: v2
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: front
    version: v2

