# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
name: Fly Deploy

on:
  push:
    branches:
      - deploy-gitactions

jobs:
  levantar_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias de servicio uno
        run: npm ci

      - name: Ejecutar tests 
        run: npm test
      
      - name: Construir la aplicación
        run: npm run build
      

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group  
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{secrets.FLY_TOKEN}}

